# our pi0_baseline.
# max_dim set to 7. language token max set to 72. all hyperparameters follows Allen
name: "pi0_baseline_bridge_paraphrase"
model_cfg: !include ../models/pi0_baseline_bridge.json
freeze_lm_head: true
task_paraphrase: true