[project]
name = "policy-server-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "msgpack>=1.0.5",
    "numpy>=1.21.6",
    "pillow>=9.0.0",
    "websockets>=11.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
